version: '2.2'
services:
    overleaf:
        image: shiftinv/overleaf:latest
        container_name: overleaf
        restart: unless-stopped
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_started
        links:
            - mongo
            - redis
        ports:
            - '127.0.0.1:7437:80'
        volumes:
            - data:/var/lib/sharelatex
        environment:
            # General options
            # Same property, unfortunately with different names in different locations
            SHARELATEX_REDIS_HOST: 'redis'
            REDIS_HOST: 'redis'

            SHARELATEX_MONGO_URL: 'mongodb://mongo/sharelatex'

            ENABLED_LINKED_FILE_TYPES: 'url,project_file'

            # Enables Thumbnail generation using ImageMagick
            ENABLE_CONVERSIONS: 'true'

            # Webserver config
            # SHARELATEX_SITE_URL: 'http://sharelatex.example.com'
            # SHARELATEX_BEHIND_PROXY: 'true'
            # SHARELATEX_SECURE_COOKIE: 'true'

            # SHARELATEX_ALLOW_PUBLIC_ACCESS: 'true'
            # SHARELATEX_ALLOW_ANONYMOUS_READ_AND_WRITE_SHARING: 'true'

            SHARELATEX_APP_NAME: 'Overleaf Community Edition'
            # SHARELATEX_NAV_TITLE: 'Our ShareLaTeX Instance'
            # SHARELATEX_HEADER_IMAGE_URL: 'http://example.com/mylogo.png'
            # SHARELATEX_ADMIN_EMAIL: 'support@example.com'

            # SHARELATEX_LEFT_FOOTER: '[{"text": "Powered by <a href=\"https://overleaf.com\">Overleaf</a> 2019"},{"text": "Another page I want to link to can be found <a href=\"here\">here</a>"} ]'
            # SHARELATEX_RIGHT_FOOTER: '[{"text": "I'm the right footer"} ]'

            # SHARELATEX_EMAIL_SMTP_HOST: 'smtp.example.com'
            # SHARELATEX_EMAIL_SMTP_PORT: '587'
            # SHARELATEX_EMAIL_SMTP_SECURE: 'true'
            # SHARELATEX_EMAIL_FROM_ADDRESS: 'sharelatex@example.com'
            # SHARELATEX_EMAIL_SMTP_USER:
            # SHARELATEX_EMAIL_SMTP_PASS:
            # SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH: 'true'
            # SHARELATEX_EMAIL_SMTP_IGNORE_TLS: 'false'
            # SHARELATEX_CUSTOM_EMAIL_FOOTER: '<div>This system is run by department x</div>'
    mongo:
        image: mongo
        restart: unless-stopped
        expose:
            - 27017
        volumes:
            - mongo_data:/data/db
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5
    redis:
        image: redis:5
        restart: unless-stopped
        expose:
            - 6379
        volumes:
            - redis_data:/data

volumes:
    data:
    mongo_data:
    redis_data:
